services:
  emqx:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/emqx/emqx:5.8.6
    container_name: emqx
    hostname: emqx-node1.cluster.local
    ports:
      - "1883:1883"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - ./emqx.conf:/opt/emqx/etc/emqx.conf
    environment:
      - EMQX_HOST=emqx-node1.cluster.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=password@123
    privileged: true
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 90s
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 16384
      net.ipv4.tcp_max_tw_buckets: 1048576
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.ip_local_port_range: "1024 65535"
    ulimits:
      nproc: 1048576
      nofile:
        soft: 1048576
        hard: 1048576

    networks:
      - demo_network

volumes:
  emqx_data:

networks:
  demo_network:
    driver: bridge
