services:
  emqx:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/emqx/emqx:5.8.6
    container_name: emqx
    hostname: emqx-node2.cluster.local
    privileged: true
    network_mode: host
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx-node2.cluster.local
      - EMQX_NODE__DATA_DIR="data"
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@emqx-node1.cluster.local,emqx@emqx-node2.cluster.local
      - EMQX_CLUSTER__AUTOHEAL=true
      - EMQX_DASHBOARD__LISTENERS__HTTP__BIND=18083
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=password@123
    volumes:
      - emqx_data:/opt/emqx/data
      - ./emqx.conf:/opt/emqx/etc/emqx.conf:ro
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 90s
    ulimits:
      nproc: 1048576
      nofile:
        soft: 1048576
        hard: 1048576

volumes:
  emqx_data:
