services:
  emqx:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/emqx/emqx:5.8.6
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
      - "4369:4369"
      - "5369:5369"
      - "6369-6370:6369-6370"
    volumes:
      - emqx_data:/opt/emqx/data
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=192.168.149.31
      - EMQX_NODE__DATA_DIR="data"
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@192.168.149.31,emqx@192.168.149.32
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=password@123
    privileged: true
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 90s
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_max_syn_backlog: 16384
      net.ipv4.tcp_max_tw_buckets: 1048576
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.ip_local_port_range: "1024 65535"
    ulimits:
      nproc: 1048576
      nofile:
        soft: 1048576
        hard: 1048576

    networks:
      - demo_network

volumes:
  emqx_data:


networks:
  demo_network:
    driver: bridge
